server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/case?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username:
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.bmw.seed.modelroot